// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjOsYnLqV0fXQPaN5JAzquTLccK_Mbt34',
    appId: '1:358715571209:web:f03b86dac841acec1e8cd8',
    messagingSenderId: '358715571209',
    projectId: 'bblove-8f2d6',
    authDomain: 'bblove-8f2d6.firebaseapp.com',
    storageBucket: 'bblove-8f2d6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcVbnN-QLM7QbpyK4aWcZX45wHO_cfT_k',
    appId: '1:358715571209:android:701901b1c71180031e8cd8',
    messagingSenderId: '358715571209',
    projectId: 'bblove-8f2d6',
    storageBucket: 'bblove-8f2d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGyhfJOtbOf1ccCrOn0d9TG1_a_pkJsSE',
    appId: '1:358715571209:ios:fc95c6ae0fe352ac1e8cd8',
    messagingSenderId: '358715571209',
    projectId: 'bblove-8f2d6',
    storageBucket: 'bblove-8f2d6.firebasestorage.app',
    iosBundleId: 'com.example.bblove',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGyhfJOtbOf1ccCrOn0d9TG1_a_pkJsSE',
    appId: '1:358715571209:ios:fc95c6ae0fe352ac1e8cd8',
    messagingSenderId: '358715571209',
    projectId: 'bblove-8f2d6',
    storageBucket: 'bblove-8f2d6.firebasestorage.app',
    iosBundleId: 'com.example.bblove',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjOsYnLqV0fXQPaN5JAzquTLccK_Mbt34',
    appId: '1:358715571209:web:22f1e15d4c6c3a7a1e8cd8',
    messagingSenderId: '358715571209',
    projectId: 'bblove-8f2d6',
    authDomain: 'bblove-8f2d6.firebaseapp.com',
    storageBucket: 'bblove-8f2d6.firebasestorage.app',
  );

}